#!/usr/bin/env python3
"""Generates the IR-7 "Zarya" reactor sprites (RSI) into Resources/Textures/_DarkSpace/Structures/Power/.

Run from the repo root:  python3 Tools/_DarkSpace/gen_reactor_sprites.py [--preview DIR]
Needs Pillow. Output is deterministic (seeded), so regenerating produces identical files.
"""
import json, math, os, random, sys
from PIL import Image

S = 32
OUT = "Resources/Textures/_DarkSpace/Structures/Power"
LICENSE = "CC-BY-SA-3.0"
COPY = "Created for Dark Space by Claude, generated by Tools/_DarkSpace/gen_reactor_sprites.py"


def new(w=S, h=S):
    return Image.new("RGBA", (w, h), (0, 0, 0, 0))


def rgba(c, a=255):
    return (c[0], c[1], c[2], c[3] if len(c) > 3 else a)


def put(im, x, y, c):
    if 0 <= x < im.width and 0 <= y < im.height:
        im.putpixel((x, y), rgba(c))


def mix(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


def mul(c, f):
    return tuple(max(0, min(255, int(v * f))) for v in c[:3])


def rect(im, x0, y0, x1, y1, c):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            put(im, x, y, c)


def hsh(*a):
    return random.Random(hash(a) & 0xFFFFFFFF if False else sum((i + 7) * 31 ** k * (v + 13) for k, (i, v) in enumerate(enumerate(a)))).random()


def px_iter(r_max=None, cx=16.0, cy=16.0):
    for y in range(S):
        for x in range(S):
            dx, dy = x + 0.5 - cx, y + 0.5 - cy
            r = math.hypot(dx, dy)
            if r_max is None or r <= r_max:
                yield x, y, dx, dy, r


# ---------------------------------------------------------------- reactor channel tile
STEEL = (46, 52, 49)


def plate():
    im = new()
    for y in range(S):
        for x in range(S):
            n = (hsh(x, y, 1) - 0.5) * 7
            c = tuple(int(v + n) for v in STEEL)
            if x == 0 or y == 0:
                c = (82, 90, 84)
            elif x == 1 or y == 1:
                c = (62, 69, 64)
            elif x == S - 1 or y == S - 1:
                c = (20, 23, 22)
            elif x == S - 2 or y == S - 2:
                c = (30, 34, 32)
            put(im, x, y, c)
    for (rx, ry) in ((3, 3), (27, 3), (3, 27), (27, 27)):
        rect(im, rx, ry, rx + 1, ry + 1, (88, 94, 88))
        put(im, rx + 1, ry + 1, (28, 30, 28))
    # painted radiation-yellow corner marks
    for i in range(4):
        put(im, 5 + i, 2, (150, 125, 30)); put(im, 26 - i, 2, (150, 125, 30))
    return im


def recess(im, dark=True):
    for x, y, dx, dy, r in px_iter(13.5):
        if r <= 11.0:
            c = (12, 13, 14) if dark else (20, 22, 22)
        elif r <= 12.2:  # inner rim, lit from top-left
            t = -(dx + dy) / (2 * r)
            c = mix((36, 40, 38), (108, 116, 108), (t + 1) / 2)
        elif r <= 13.5:  # outer bevel
            t = (dx + dy) / (2 * r)
            c = mix((24, 27, 26), (74, 82, 76), (t + 1) / 2)
        put(im, x, y, c)


def shade(c, dx, dy, k=0.5):
    return mul(c, 1 - (dx + dy) / 21.0 * k)


CAP_R = 10.4


def cap_empty(im):
    for x, y, dx, dy, r in px_iter(CAP_R):
        c = mix((16, 17, 19), (2, 2, 3), 1 - r / CAP_R)
        put(im, x, y, c)
    for i in range(-8, 9, 4):  # grating
        for k in range(-9, 10):
            for (ax, ay) in ((16 + i, 16 + k), (16 + k, 16 + i)):
                if math.hypot(ax - 15.5, ay - 15.5) <= CAP_R - 0.6:
                    put(im, ax, ay, (58, 63, 60) if (k + i) % 2 else (40, 44, 42))


def cap_fuel(im):
    for x, y, dx, dy, r in px_iter(CAP_R):
        c = shade((56, 84, 52), dx, dy)
        if 8.6 <= r <= 9.4:
            c = (28, 44, 28)
        put(im, x, y, c)
    for k in range(6):  # bolts
        a = k * math.pi / 3 + 0.5
        bx, by = int(16 + 7.4 * math.cos(a)) - 1, int(16 + 7.4 * math.sin(a)) - 1
        rect(im, bx, by, bx + 1, by + 1, (110, 118, 108)); put(im, bx + 1, by + 1, (40, 44, 40))
    for x, y, dx, dy, r in px_iter(5.2):
        if r < 4.6:
            put(im, x, y, (20, 30, 20))
    for x, y, dx, dy, r in px_iter(4.2):  # radiation trefoil
        if 1.5 <= r <= 4.2 and (math.degrees(math.atan2(dy, dx)) + 90) % 120 < 60:
            put(im, x, y, (232, 200, 40))
    rect(im, 15, 15, 16, 16, (232, 200, 40))


def cap_rod(im):
    for x, y, dx, dy, r in px_iter(CAP_R):
        c = shade((50, 68, 100), dx, dy)
        if 8.6 <= r <= 9.4:
            c = (26, 34, 54)
        put(im, x, y, c)
    for (ox, oy) in ((0, -1), (1, 0), (0, 1), (-1, 0)):  # amber graduation ticks
        for k in range(6, 9):
            put(im, int(15.5 + ox * k + (0 if ox == 0 else 0)), int(15.5 + oy * k), (214, 152, 40))
            if ox == 0: put(im, 16, int(15.5 + oy * k), (214, 152, 40))
            else: put(im, int(15.5 + ox * k), 16, (214, 152, 40))
    for x, y, dx, dy, r in px_iter(5.2):  # the rod itself
        if r < 5.0:
            put(im, x, y, mix((90, 104, 130), (22, 26, 40), min(1, r / 5) ** 0.7 * 0.0 + (dx + dy + 7) / 14))
    for x, y, dx, dy, r in px_iter(3.0):
        put(im, x, y, mix((150, 172, 210), (34, 42, 66), (dx + dy + 4) / 8))
    put(im, 14, 14, (200, 220, 245))


def cap_graphite(im):
    for x, y, dx, dy, r in px_iter(CAP_R):
        c = shade((38, 38, 43), dx, dy, 0.6)
        if (int(x) % 5 == 0) or (int(y) % 5 == 0):
            c = mul(c, 1.5)
        c = mul(c, 0.9 + hsh(x, y, 5) * 0.2)
        if 9.0 <= r:
            c = (22, 22, 26)
        put(im, x, y, c)
    for (bx, by) in ((11, 11), (19, 19)):  # a couple of glossy blocks
        put(im, bx, by, (96, 96, 108)); put(im, bx + 1, by, (76, 76, 88))


CAPS = {"empty": cap_empty, "fuel": cap_fuel, "rod": cap_rod, "graphite": cap_graphite}


def cracks(seed, n=3):
    rnd = random.Random(seed)
    pts = []
    for _ in range(n):
        a = rnd.uniform(0, 2 * math.pi)
        x, y = 16 + 11 * math.cos(a), 16 + 11 * math.sin(a)
        d = a + math.pi + rnd.uniform(-0.5, 0.5)
        for _ in range(rnd.randint(8, 13)):
            pts.append((int(x), int(y)))
            d += rnd.uniform(-0.6, 0.6)
            x += math.cos(d); y += math.sin(d)
    return pts


def damage_base(im, kind, seed):
    rnd = random.Random(seed)
    for x, y, dx, dy, r in px_iter(CAP_R):  # soot
        v = hsh(x // 2, y // 2, seed)
        if v > 0.55 and kind != "empty":
            put(im, x, y, mul(im.getpixel((x, y)), 0.5))
    a0 = rnd.uniform(0, 2 * math.pi)
    for x, y, dx, dy, r in px_iter(CAP_R + 1):  # chunk missing from the cap edge
        da = (math.atan2(dy, dx) - a0 + math.pi) % (2 * math.pi) - math.pi
        if r > 6.5 - 2 * math.cos(da * 3) and abs(da) < 0.55:
            put(im, x, y, (5, 5, 6))
    for (x, y) in cracks(seed):
        put(im, x, y, (6, 6, 7))
    for (rx, ry) in ((3, 27), (27, 3)):  # a bent rivet
        rect(im, rx, ry, rx + 1, ry + 1, (20, 20, 20))
    for i in range(6):  # scorch on plate
        put(im, 2 + i, 29 - i // 2, (20, 20, 18))


def render(kind, cond, t=0, n=1):
    """Returns (base, glow); glow is meant to be drawn unshaded on top of base."""
    seed = {"empty": 1, "fuel": 2, "rod": 3, "graphite": 4}[kind] * 11
    base = plate(); recess(base); CAPS[kind](base)
    if cond == "damaged":
        damage_base(base, kind, seed)
    glow = new()
    ph = 2 * math.pi * t / max(n, 1)
    if kind == "fuel":  # Cherenkov glow of a live fuel channel
        for x, y, dx, dy, r in px_iter(9.6):
            a = (0.26 + 0.20 * math.sin(ph)) * (1 - (r / 10) ** 2) + 0.10
            put(glow, x, y, (90, 220, 255, int(255 * min(a, 0.9))))
        for x, y, dx, dy, r in px_iter(2.2):
            put(glow, x, y, (200, 250, 255, int(255 * (0.55 + 0.3 * math.sin(ph)))))
    if cond == "hot":
        p = 0.6 + 0.4 * math.sin(ph + 1.0)
        for x, y, dx, dy, r in px_iter(16.5):
            if r <= 9.6:
                a = 0.16 + 0.12 * p
                col = (255, 96, 24)
            elif r <= 12.6:
                a = 0.55 * p + 0.2
                col = (255, 120, 30)
            elif r <= 16.5:
                a = 0.20 * p * (1 - (r - 12.6) / 3.9)
                col = (255, 90, 20)
            else:
                continue
            put(glow, x, y, col + (int(255 * a),))
        if kind == "fuel":
            for x, y, dx, dy, r in px_iter(3.0):
                put(glow, x, y, (255, 235, 170, int(255 * (0.6 + 0.3 * p))))
    if cond == "damaged":
        pts = cracks({"empty": 11, "fuel": 22, "rod": 33, "graphite": 44}[kind])
        for i, (x, y) in enumerate(pts):
            if i % 3 == 0 and hsh(i, t, 9) > 0.45:
                put(glow, x, y, (255, 150, 40, 235) if hsh(i, t, 4) > 0.4 else (255, 215, 90, 255))
        rr = random.Random(seed + t * 17)  # sparks
        if t % 2 == 0:
            sx, sy = rr.randint(6, 25), rr.randint(6, 25)
            put(glow, sx, sy, (255, 240, 160, 255))
            put(glow, sx + 1, sy, (255, 190, 70, 160))
    return base, glow


def comp(base, glow):
    return Image.alpha_composite(base, glow)


# ---------------------------------------------------------------- corium / meltdown
def blob(t, n, radius, seed=0, full=False, crust=False):
    im = new()
    ph = 2 * math.pi * t / n
    rr = random.Random(seed)
    for x, y, dx, dy, r in px_iter():
        a = math.atan2(dy, dx)
        wob = 1.6 * math.sin(3 * a + 1.1 + seed) + 1.1 * math.sin(5 * a - 0.7 * seed + ph) + 0.7 * math.sin(2 * a + ph)
        edge = (radius + wob) - r if not full else 9.0
        if edge <= 0:
            continue
        sw = math.sin(x * 0.55 + ph + seed) + math.sin(y * 0.5 - ph) + math.sin((x + y) * 0.35 + ph * 1.0)
        heat = min(1.0, edge / 5.0) * 0.55 + (sw + 3) / 6 * 0.45
        if full:
            heat = (sw + 3) / 6
        if crust:
            heat = 0.0 if hsh(x // 3, y // 3, seed) > 0.28 else 0.55 + 0.2 * math.sin(ph + x)
            c = mix((22, 20, 21), (200, 60, 16), heat) if heat else mul((36, 32, 33), 0.8 + hsh(x, y, 3) * 0.5)
        elif heat < 0.30:
            c = mix((36, 16, 12), (170, 38, 12), heat / 0.30)
        elif heat < 0.62:
            c = mix((170, 38, 12), (255, 122, 22), (heat - 0.30) / 0.32)
        else:
            c = mix((255, 122, 22), (255, 236, 150), (heat - 0.62) / 0.38)
        put(im, x, y, c)
    if not crust:
        for i in range(4):  # bubbles
            bx, by = rr.randint(8, 23), rr.randint(8, 23)
            if hsh(i, t, seed) > 0.4 and im.getpixel((bx, by))[3]:
                put(im, bx, by, (255, 250, 200)); put(im, bx + 1, by, (255, 200, 90))
    return im


def render_melted(t, n):
    base = plate(); recess(base, dark=True)
    for x, y, dx, dy, r in px_iter(16):  # scorched plate
        if base.getpixel((x, y))[3] and 12.2 < r < 16:
            put(base, x, y, mul(base.getpixel((x, y)), 0.45))
    pool = blob(t, n, 10.6, seed=2)
    return comp(base, pool)


# ---------------------------------------------------------------- floor
def floor_states():
    st = {}
    st["plate"] = [plate()]
    worn = plate()
    for x, y, dx, dy, r in px_iter():
        v = hsh(x, y, 77)
        if v > 0.93: put(worn, x, y, (26, 28, 27))
        elif v < 0.03: put(worn, x, y, (96, 78, 52))
    st["plate-worn"] = [worn]
    hz = new()
    for y in range(S):
        for x in range(S):
            put(hz, x, y, (200, 165, 25) if ((x + y) // 4) % 2 == 0 else (24, 24, 22))
    for i in range(S):
        for k in (0, 1, S - 1, S - 2):
            put(hz, i, k, (18, 18, 18)); put(hz, k, i, (18, 18, 18))
    st["hazard"] = [hz]
    return st


# ---------------------------------------------------------------- SUZ console
OLIVE = (52, 62, 50)


def console_dir(d):
    """d: 0 south (front), 1 north (back), 2 east, 3 west (side profiles)"""
    im = new()
    if d == 0:
        rect(im, 3, 4, 28, 29, (24, 28, 25))                    # outline
        rect(im, 4, 5, 27, 28, OLIVE)
        rect(im, 4, 5, 27, 5, (84, 96, 82))                    # top highlight
        rect(im, 6, 6, 25, 17, (26, 30, 28))                   # monitor bezel
        rect(im, 8, 7, 23, 15, (8, 12, 9))                     # screen (glow layer draws into this)
        for k in range(5):                                     # lamp row (dark in the base)
            rect(im, 8 + k * 3, 17, 9 + k * 3, 17, (34, 38, 34))
        rect(im, 4, 18, 27, 24, (66, 76, 62))                  # slanted control panel
        rect(im, 4, 18, 27, 18, (98, 110, 94))
        rect(im, 4, 24, 27, 24, (30, 36, 30))
        for (kx, col) in ((7, (208, 150, 40)), (11, (140, 146, 138)), (15, (140, 146, 138))):
            rect(im, kx, 20, kx + 2, 22, (28, 30, 28)); rect(im, kx, 20, kx + 1, 21, col)
        for k in range(4):                                     # toggle rows
            put(im, 8 + k * 2, 23, (170, 176, 168)); put(im, 8 + k * 2, 22, (40, 44, 40)) if False else None
        # AZ-5: red button under a yellow/black guard
        rect(im, 20, 19, 26, 23, (200, 165, 25))
        for i in range(7):
            if i % 2: put(im, 20 + i, 19, (24, 24, 22)); put(im, 20 + i, 23, (24, 24, 22))
        rect(im, 21, 20, 25, 22, (110, 14, 12))
        rect(im, 22, 20, 24, 22, (206, 40, 30)); put(im, 22, 20, (255, 130, 110))
        rect(im, 6, 26, 25, 27, (38, 44, 38))                  # lower cabinet, vents
        for k in range(6, 26, 2):
            put(im, k, 26, (18, 20, 18)); put(im, k, 27, (60, 68, 58))
        rect(im, 4, 29, 6, 29, (16, 18, 16)); rect(im, 25, 29, 27, 29, (16, 18, 16))
        for (x, y) in ((5, 6), (26, 6), (5, 27), (26, 27)):
            put(im, x, y, (110, 116, 108))
    elif d == 1:
        rect(im, 3, 4, 28, 29, (22, 26, 23)); rect(im, 4, 5, 27, 28, mul(OLIVE, 0.78))
        rect(im, 4, 5, 27, 5, (70, 80, 68))
        for k in range(8, 26, 2):
            rect(im, 7, k - 2, 24, k - 2, (24, 28, 25)) if k < 24 else None
        rect(im, 10, 22, 21, 27, (30, 34, 30))
        for k in range(11, 21, 2): rect(im, k, 23, k, 26, (52, 58, 50))
        for k in range(3):
            put(im, 6 + k * 9, 8, (150, 40, 30)); put(im, 7 + k * 9, 8, (120, 30, 24))
    else:
        x0, x1 = (6, 26) if d == 2 else (5, 25)
        rect(im, x0 - 1, 4, x1 + 1, 29, (24, 28, 25)); rect(im, x0, 5, x1, 28, mul(OLIVE, 0.9))
        rect(im, x0, 5, x1, 6, (84, 96, 82))
        hx = (x0 + 2, x1 - 2) if d == 2 else (x1 - 2, x0 + 2)
        for y in range(8, 17):                                 # monitor housing seen from the side
            xs = (x0 + 3, x0 + 3 + (16 - y) // 2 + 4) if d == 2 else (x1 - 3 - (16 - y) // 2 - 4, x1 - 3)
            rect(im, xs[0], y, xs[1], y, (30, 34, 32))
        for k in range(20, 28, 2):
            rect(im, x0 + 2, k, x1 - 2, k, (30, 36, 30))
    return im


def console_screen(d, mode, t, n):
    im = new()
    if d != 0:
        return im
    ph = 2 * math.pi * t / n
    if mode == "off":
        for y in range(7, 16):
            for x in range(8, 24):
                put(im, x, y, (10, 16, 12, 255))
        put(im, 9, 8, (60, 80, 64)); put(im, 10, 8, (44, 60, 48))
        return im
    alarm = mode == "alarm"
    on = (t % 2 == 0)
    col = (255, 70, 50) if alarm else (110, 255, 140)
    dim = mul(col, 0.35)
    for y in range(7, 16):
        for x in range(8, 24):
            put(im, x, y, (40, 8, 6, 255) if alarm and on else (6, 22, 12, 255) if not alarm else (14, 6, 6, 255))
    if alarm:
        if on:
            for k in range(10, 22):  # flashing exclamation band
                put(im, k, 7, col)
                put(im, k, 15, col)
            for y in range(8, 13): rect(im, 15, y, 16, y, col)
            rect(im, 15, 14, 16, 14, col)
        else:
            for y in (9, 11, 13): rect(im, 9, y, 22, y, dim)
    else:
        for k in range(5):  # bars: zone power / temperature / rods
            h = int(2 + 5 * (0.5 + 0.5 * math.sin(ph + k * 1.3)))
            rect(im, 9 + k * 3, 15 - h, 10 + k * 3, 14, col if k % 2 == 0 else (230, 200, 60))
        for x in range(9, 23):  # scrolling trace
            y = 8 + int(1.4 + 1.3 * math.sin(x * 0.7 - ph * 2))
            put(im, x, y, dim if x % 2 else col)
    lamps = [(90, 230, 110), (90, 230, 110), (230, 190, 50), (60, 70, 60), (60, 70, 60)]
    if alarm:
        lamps = [(230, 50, 40) if on else (90, 30, 26)] * 3 + [(230, 190, 50), (60, 70, 60)]
    for k, lc in enumerate(lamps):
        rect(im, 8 + k * 3, 17, 9 + k * 3, 17, lc)
    return im


# ---------------------------------------------------------------- writing
def strip(frames):
    im = new(S * len(frames), S)
    for i, f in enumerate(frames):
        im.paste(f, (S * i, 0))
    return im


def write_rsi(path, states):
    """states: list of (name, frames|list-of-dirs, delay, dirs)"""
    os.makedirs(path, exist_ok=True)
    meta = {"version": 1, "license": LICENSE, "copyright": COPY, "size": {"x": S, "y": S}, "states": []}
    for name, frames, delay, dirs in states:
        strip(frames).save(os.path.join(path, name + ".png"))
        e = {"name": name}
        if dirs > 1:
            e["directions"] = dirs
        if delay:
            per = len(frames) // dirs
            e["delays"] = [[delay] * per for _ in range(dirs)]
        meta["states"].append(e)
    with open(os.path.join(path, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2); f.write("\n")


def main():
    preview_dir = None
    if "--preview" in sys.argv:
        preview_dir = sys.argv[sys.argv.index("--preview") + 1]
    registry = {}

    # channel tiles
    ch, ov = [], []
    combos = [("empty", "normal", 1), ("empty", "damaged", 4),
              ("fuel", "normal", 4), ("fuel", "hot", 4), ("fuel", "damaged", 4),
              ("rod", "normal", 1), ("rod", "hot", 4), ("rod", "damaged", 4),
              ("graphite", "normal", 1), ("graphite", "hot", 4), ("graphite", "damaged", 4)]
    for kind, cond, n in combos:
        name = kind if cond == "normal" else f"{kind}-{cond}"
        frames = [comp(*render(kind, cond, t, n)) for t in range(n)]
        ch.append((name, frames, 0.25 if n > 1 else 0, 1))
        registry[name] = frames
    # melted channel
    mf = [render_melted(t, 4) for t in range(4)]
    ch.append(("melted", mf, 0.2, 1)); registry["melted"] = mf
    # unshaded overlays for code that wants a separate glow layer
    ov.append(("glow-fuel", [render("fuel", "normal", t, 4)[1] for t in range(4)], 0.25, 1))
    ov.append(("glow-hot", [render("rod", "hot", t, 4)[1] for t in range(4)], 0.25, 1))
    ov.append(("glow-damaged", [render("rod", "damaged", t, 4)[1] for t in range(4)], 0.25, 1))
    # bare hall floor variants live next to the channel tiles
    fl = floor_states()
    ch += [(k, v, 0, 1) for k, v in fl.items()]
    write_rsi(f"{OUT}/reactor_channel.rsi", ch + ov)

    # corium and meltdown
    co = [
        ("corium", [blob(t, 4, 12.5, seed=1) for t in range(4)], 0.25, 1),
        ("corium-crust", [blob(t, 2, 12.5, seed=1, crust=True) for t in range(2)], 0.6, 1),
        ("meltdown", [blob(t, 4, 0, seed=3, full=True) for t in range(4)], 0.2, 1),
    ]
    for name, fr, _, _ in co: registry[name] = fr
    write_rsi(f"{OUT}/reactor_corium.rsi", co)

    # SUZ console: body has 4 directions (S, N, E, W); screen overlays are unshaded
    body = [console_dir(d) for d in range(4)]
    scr = {m: [console_screen(d, m, t, 4) for d in range(4) for t in range(4)] for m in ("on", "alarm")}
    scr["off"] = [console_screen(d, "off", 0, 1) for d in range(4)]
    write_rsi(f"{OUT}/suz_console.rsi", [
        ("suz", body, 0, 4),
        ("screen-on", scr["on"], 0.3, 4),
        ("screen-alarm", scr["alarm"], 0.35, 4),
        ("screen-off", scr["off"], 0, 4),
    ])
    registry["console_body"] = body[:1]
    registry["console_on"] = [comp(body[0], scr["on"][t]) for t in range(4)]
    registry["console_alarm"] = [comp(body[0], scr["alarm"][t]) for t in range(4)]
    registry["console_back"] = [body[1]]; registry["console_e"] = [body[2]]; registry["console_w"] = [body[3]]
    print("wrote RSIs to", OUT)

    if preview_dir:
        make_preview(registry, preview_dir)


def make_preview(reg, outdir):
    os.makedirs(outdir, exist_ok=True)
    bg = (14, 15, 16, 255)
    layout = ["GFGFG", "FRFRF", "GFGFG", "FRFRF", "GFGFG"]
    kmap = {"G": "graphite", "F": "fuel", "R": "rod", ".": "empty"}

    def grid(fn, t):
        im = Image.new("RGBA", (S * 5, S * 5), bg)
        for r, row in enumerate(layout):
            for c, ch in enumerate(row):
                k = kmap[ch]
                cond = fn(r, c, k)
                name = k if cond == "normal" else f"{k}-{cond}"
                if name not in reg: name = k
                fr = reg[name]
                if cond == "melted": fr = reg["melted"]
                im.alpha_composite(fr[t % len(fr)], (c * S, r * S))
        return im

    def hotmix(r, c, k):
        d = math.hypot(r - 2, c - 2)
        if d < 1.2: return "melted"
        if d < 2.3: return "hot"
        if (r * 3 + c) % 7 == 0: return "damaged"
        return "normal"

    scale = 5
    scenes = [lambda r, c, k: "normal", lambda r, c, k: "hot", lambda r, c, k: "damaged", hotmix]
    labels = ["norm", "hot", "dmg", "meltdown"]
    frames = []
    for t in range(4):
        sheet = Image.new("RGBA", (S * 5 * 4 + 30 * 3 + 40, S * 5 + 40), bg)
        x = 20
        for sc in scenes:
            g = grid(sc, t)
            sheet.alpha_composite(g, (x, 20)); x += S * 5 + 30
        frames.append(sheet)
    a = frames[0].resize((frames[0].width * 2, frames[0].height * 2), Image.NEAREST)
    # state catalogue
    names = [n for n in reg]
    cols = 8
    rows = (len(names) + cols - 1) // cols
    cat = Image.new("RGBA", (cols * (S + 6) + 6, rows * (S + 6) + 6), bg)
    for i, n in enumerate(names):
        cat.alpha_composite(reg[n][0], (6 + (i % cols) * (S + 6), 6 + (i // cols) * (S + 6)))
    cat = cat.resize((cat.width * 4, cat.height * 4), Image.NEAREST)
    a.save(os.path.join(outdir, "reactor_grids.png"))
    cat.save(os.path.join(outdir, "reactor_catalogue.png"))
    big = [f.resize((f.width * 2, f.height * 2), Image.NEAREST).convert("P", palette=Image.ADAPTIVE) for f in frames]
    big[0].save(os.path.join(outdir, "reactor_grids.gif"), save_all=True, append_images=big[1:], duration=250, loop=0)
    # console + corium row
    row = Image.new("RGBA", (S * 10 + 20 * 2 + 6, S * 2 + 20), bg)
    for i, n in enumerate(["console_body", "console_on", "console_alarm", "console_back", "console_e", "console_w"]):
        row.alpha_composite(reg[n][0 if n != "console_alarm" else 0], (10 + i * (S + 6), 10))
        if n in ("console_on", "console_alarm"): row.alpha_composite(reg[n][1], (10 + i * (S + 6), 10 + S + 4))
    for i, n in enumerate(["corium", "corium-crust", "meltdown"]):
        row.alpha_composite(reg[n][1 % len(reg[n])], (10 + (6 + i) * (S + 6) + 10, 10))
    row.resize((row.width * 5, row.height * 5), Image.NEAREST).save(os.path.join(outdir, "reactor_console_corium.png"))
    print("preview in", outdir)


if __name__ == "__main__":
    main()
